services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
    restart: unless-stopped
    environment:
      - NODE_ENV=production
